// data.js

const questions = [
  {
    id: 1,
    type: "preposition",
    question: "She is responsible ___ preparing the financial report.",
    choices: ["to", "for", "with", "about"],
    answer: "for",
    translation: "彼女は財務報告の作成に責任がある",
    comment: "responsible for（責任がある）",
  },
  {
    id: 2,
    type: "preposition",
    question: "The manager apologized ___ the delay.",
    choices: ["to", "for", "about", "with"],
    answer: "for",
    translation: "マネージャーは遅延について謝罪した",
    comment: "apologize for（〜を謝る）",
  },
  {
    id: 3,
    type: "preposition",
    question: "We are interested ___ expanding our business overseas.",
    choices: ["in", "on", "at", "for"],
    answer: "in",
    translation: "私たちは海外展開に興味がある",
    comment: "interested in（興味がある）",
  },
  {
    id: 4,
    type: "preposition",
    question: "Please apply ___ the position by Friday.",
    choices: ["to", "at", "for", "in"],
    answer: "for",
    translation: "金曜日までにその職に応募してください",
    comment: "apply for（応募する）",
  },
  {
    id: 5,
    type: "preposition",
    question: "The company will participate ___ the trade fair.",
    choices: ["at", "in", "on", "to"],
    answer: "in",
    translation: "その会社は展示会に参加する予定だ",
    comment: "participate in（参加する）",
  },
  {
    id: 6,
    type: "preposition",
    question: "This software is capable ___ handling large amounts of data.",
    choices: ["to", "for", "of", "with"],
    answer: "of",
    translation: "このソフトは大量のデータを処理できる",
    comment: "capable of（〜できる）",
  },
  {
    id: 7,
    type: "preposition",
    question: "The meeting has been postponed ___ next Monday.",
    choices: ["until", "by", "at", "in"],
    answer: "until",
    translation: "会議は来週月曜日まで延期された",
    comment: "until（〜まで延期）",
  },
  {
    id: 8,
    type: "preposition",
    question: "He is in charge ___ customer support.",
    choices: ["for", "with", "of", "to"],
    answer: "of",
    translation: "彼はカスタマーサポートを担当している",
    comment: "in charge of（担当する）",
  },
  {
    id: 9,
    type: "preposition",
    question: "We are looking forward ___ hearing from you.",
    choices: ["for", "at", "to", "with"],
    answer: "to",
    translation: "あなたからの連絡を楽しみにしています",
    comment: "look forward to（楽しみにする）",
  },
  {
    id: 10,
    type: "preposition",
    question: "The new policy will have an impact ___ employee morale.",
    choices: ["to", "in", "at", "on"],
    answer: "on",
    translation: "新しい方針は従業員の士気に影響を与える",
    comment: "impact on（影響を与える）",
  },

  {
    id: 11,
    type: "preposition",
    question: "She is responsible ___ the marketing strategy.",
    choices: ["for", "in", "on", "of"],
    answer: "for",
    translation: "彼女はマーケティング戦略を担当している",
    comment: "responsible for",
  },
  {
    id: 12,
    type: "preposition",
    question: "We participated ___ the annual conference.",
    choices: ["for", "in", "on", "with"],
    answer: "in",
    translation: "私たちは年次会議に参加した",
    comment: "participate in",
  },
  {
    id: 13,
    type: "preposition",
    question: "The results depend ___ customer feedback.",
    choices: ["on", "in", "for", "of"],
    answer: "on",
    translation: "結果は顧客のフィードバックに依存する",
    comment: "depend on",
  },
  {
    id: 14,
    type: "preposition",
    question: "He is capable ___ solving complex problems.",
    choices: ["of", "for", "to", "with"],
    answer: "of",
    translation: "彼は複雑な問題を解決できる",
    comment: "capable of",
  },
  {
    id: 15,
    type: "preposition",
    question: "I’m looking forward ___ meeting you.",
    choices: ["to", "for", "on", "in"],
    answer: "to",
    translation: "あなたに会うのを楽しみにしています",
    comment: "look forward to + ing",
  },
  {
    id: 16,
    type: "preposition",
    question: "This product has a strong impact ___ sales.",
    choices: ["on", "to", "in", "for"],
    answer: "on",
    translation: "この製品は売上に大きな影響を与える",
    comment: "impact on",
  },
  {
    id: 17,
    type: "preposition",
    question: "She provided the clients ___ detailed information.",
    choices: ["with", "to", "for", "of"],
    answer: "with",
    translation: "彼女は顧客に詳細な情報を提供した",
    comment: "provide A with B",
  },
  {
    id: 18,
    type: "preposition",
    question: "The team is satisfied ___ the outcome.",
    choices: ["with", "in", "on", "for"],
    answer: "with",
    translation: "チームは結果に満足している",
    comment: "satisfied with",
  },
  {
    id: 19,
    type: "preposition",
    question: "He succeeded ___ completing the project.",
    choices: ["in", "on", "for", "to"],
    answer: "in",
    translation: "彼はプロジェクトの完了に成功した",
    comment: "succeed in",
  },
  {
    id: 20,
    type: "preposition",
    question: "She is in charge ___ human resources.",
    choices: ["of", "for", "to", "with"],
    answer: "of",
    translation: "彼女は人事を担当している",
    comment: "in charge of",
  },
  {
    id: 21,
    type: "preposition",
    question: "Employees are encouraged to participate ___ training sessions.",
    choices: ["in", "on", "at", "for"],
    answer: "in",
    translation: "従業員は研修に参加するよう奨励されている",
    comment: "participate in（中に入って参加）",
  },
  {
    id: 22,
    type: "preposition",
    question: "The company is responsible ___ ensuring customer satisfaction.",
    choices: ["for", "to", "with", "about"],
    answer: "for",
    translation: "会社は顧客満足を確保する責任がある",
    comment: "responsible for（担当・責任）",
  },
  {
    id: 23,
    type: "preposition",
    question: "We apologize ___ any inconvenience caused.",
    choices: ["for", "about", "to", "with"],
    answer: "for",
    translation: "ご不便をおかけしたことをお詫びします",
    comment: "apologize for（理由に対して謝る）",
  },
  {
    id: 24,
    type: "preposition",
    question: "The success depends ___ communication.",
    choices: ["on", "in", "for", "with"],
    answer: "on",
    translation: "成功はコミュニケーションにかかっている",
    comment: "depend on（それにくっついて依存）",
  },
  {
    id: 25,
    type: "preposition",
    question: "The manager is in charge ___ daily operations.",
    choices: ["of", "for", "with", "to"],
    answer: "of",
    translation: "マネージャーは日々の業務を担当している",
    comment: "in charge of（担当している）",
  },

  {
    id: 26,
    type: "preposition",
    question: "Customers are satisfied ___ our service.",
    choices: ["with", "in", "on", "for"],
    answer: "with",
    translation: "顧客は私たちのサービスに満足している",
    comment: "satisfied with（一緒に持って満足）",
  },
  {
    id: 27,
    type: "preposition",
    question: "The policy will have an impact ___ businesses.",
    choices: ["on", "to", "in", "for"],
    answer: "on",
    translation: "その政策は企業に影響を与える",
    comment: "impact on（接触して影響）",
  },
  {
    id: 28,
    type: "preposition",
    question: "We look forward ___ working with you.",
    choices: ["to", "for", "on", "in"],
    answer: "to",
    translation: "あなたと働くのを楽しみにしています",
    comment: "look forward to（未来へ向かう）",
  },
  {
    id: 29,
    type: "preposition",
    question: "The company provides employees ___ training.",
    choices: ["with", "to", "for", "of"],
    answer: "with",
    translation: "会社は従業員に研修を提供する",
    comment: "provide A with B（AにBを持たせる）",
  },
  {
    id: 30,
    type: "preposition",
    question: "He succeeded ___ increasing sales.",
    choices: ["in", "on", "for", "to"],
    answer: "in",
    translation: "彼は売上向上に成功した",
    comment: "succeed in（中で成功）",
  },

  {
    id: 31,
    type: "preposition",
    question: "The report is based ___ reliable data.",
    choices: ["on", "in", "at", "for"],
    answer: "on",
    translation: "その報告書は信頼できるデータに基づいている",
    comment: "based on（上に乗っている）",
  },
  {
    id: 32,
    type: "preposition",
    question: "She is capable ___ handling pressure.",
    choices: ["of", "for", "to", "with"],
    answer: "of",
    translation: "彼女はプレッシャーに対処できる",
    comment: "capable of（能力を持つ）",
  },
  {
    id: 33,
    type: "preposition",
    question: "The team is engaged ___ development.",
    choices: ["in", "on", "at", "for"],
    answer: "in",
    translation: "チームは開発に従事している",
    comment: "engaged in（活動の中にいる）",
  },
  {
    id: 34,
    type: "preposition",
    question: "The meeting was postponed ___ Friday.",
    choices: ["until", "by", "at", "on"],
    answer: "until",
    translation: "会議は金曜日まで延期された",
    comment: "until（〜まで）",
  },
  {
    id: 35,
    type: "preposition",
    question: "We must focus ___ customer needs.",
    choices: ["on", "in", "at", "for"],
    answer: "on",
    translation: "顧客のニーズに集中しなければならない",
    comment: "focus on（対象に接触）",
  },

  {
    id: 36,
    type: "preposition",
    question: "The company consists ___ several divisions.",
    choices: ["of", "in", "for", "with"],
    answer: "of",
    translation: "その会社はいくつかの部門で構成されている",
    comment: "consist of（〜で構成）",
  },
  {
    id: 37,
    type: "preposition",
    question: "He responded ___ the request immediately.",
    choices: ["to", "for", "on", "with"],
    answer: "to",
    translation: "彼はその要求にすぐ対応した",
    comment: "respond to（矢印の方向）",
  },
  {
    id: 38,
    type: "preposition",
    question: "The project finished ahead ___ schedule.",
    choices: ["of", "in", "on", "for"],
    answer: "of",
    translation: "プロジェクトは予定より早く終わった",
    comment: "ahead of（〜より前）",
  },
  {
    id: 39,
    type: "preposition",
    question: "She is aware ___ the risks.",
    choices: ["of", "for", "in", "on"],
    answer: "of",
    translation: "彼女はリスクを認識している",
    comment: "aware of（認識している）",
  },
  {
    id: 40,
    type: "preposition",
    question: "The company is known ___ quality.",
    choices: ["for", "to", "with", "in"],
    answer: "for",
    translation: "その会社は品質で知られている",
    comment: "known for（理由で知られる）",
  },

  {
    id: 41,
    type: "preposition",
    question: "We must deal ___ complaints quickly.",
    choices: ["with", "to", "for", "in"],
    answer: "with",
    translation: "苦情には迅速に対処しなければならない",
    comment: "deal with（対処する）",
  },
  {
    id: 42,
    type: "preposition",
    question: "The changes will affect ___ profits.",
    choices: ["(no preposition)", "on", "to", "for"],
    answer: "(no preposition)",
    translation: "その変更は利益に影響を与える",
    comment: "affectは前置詞不要",
  },
  {
    id: 43,
    type: "preposition",
    question: "The manager discussed the issue ___ the team.",
    choices: ["(no preposition)", "about", "on", "with"],
    answer: "(no preposition)",
    translation: "マネージャーはその問題をチームと議論した",
    comment: "discussは前置詞不要",
  },
  {
    id: 44,
    type: "preposition",
    question: "She entered ___ the room quietly.",
    choices: ["(no preposition)", "into", "to", "in"],
    answer: "(no preposition)",
    translation: "彼女は静かに部屋に入った",
    comment: "enterは前置詞不要",
  },
  {
    id: 45,
    type: "preposition",
    question: "The company plans to expand ___ new markets.",
    choices: ["into", "in", "to", "on"],
    answer: "into",
    translation: "会社は新市場に進出する予定だ",
    comment: "into（中に入る方向）",
  },

  {
    id: 46,
    type: "preposition",
    question: "He is accustomed ___ working overtime.",
    choices: ["to", "for", "with", "in"],
    answer: "to",
    translation: "彼は残業に慣れている",
    comment: "accustomed to（慣れている）",
  },
  {
    id: 47,
    type: "preposition",
    question: "The strategy resulted ___ higher profits.",
    choices: ["in", "on", "for", "to"],
    answer: "in",
    translation: "その戦略は利益増加につながった",
    comment: "result in（結果として）",
  },
  {
    id: 48,
    type: "preposition",
    question: "The manager is pleased ___ the results.",
    choices: ["with", "on", "for", "in"],
    answer: "with",
    translation: "マネージャーは結果に満足している",
    comment: "pleased with",
  },
  {
    id: 49,
    type: "preposition",
    question: "The company invested ___ new technology.",
    choices: ["in", "on", "for", "with"],
    answer: "in",
    translation: "会社は新技術に投資した",
    comment: "invest in",
  },
  {
    id: 50,
    type: "preposition",
    question: "Employees must comply ___ company rules.",
    choices: ["with", "to", "for", "on"],
    answer: "with",
    translation: "従業員は会社の規則に従わなければならない",
    comment: "comply with（従う）",
  },

  {
    id: 51,
    type: "part_of_speech",
    question: "The company made a significant ______ in its strategy.",
    choices: ["change", "changing", "changed", "changeable"],
    answer: "change",
    translation: "その会社は戦略に大きな変更を加えた",
    comment: "a + 形容詞の後は名詞",
  },
  {
    id: 52,
    type: "part_of_speech",
    question: "Employees must respond ______ to all inquiries.",
    choices: ["prompt", "promptly", "prompting", "promptness"],
    answer: "promptly",
    translation: "従業員はすべての問い合わせに迅速に対応しなければならない",
    comment: "動詞を修飾 → 副詞",
  },
  {
    id: 53,
    type: "part_of_speech",
    question: "The manager gave a very ______ explanation.",
    choices: ["clear", "clearly", "clarity", "clearing"],
    answer: "clear",
    translation: "マネージャーはとても分かりやすい説明をした",
    comment: "very の後は形容詞",
  },
  {
    id: 54,
    type: "part_of_speech",
    question: "The report was ______ by the director.",
    choices: ["approve", "approving", "approved", "approval"],
    answer: "approved",
    translation: "その報告書は部長によって承認された",
    comment: "be動詞 + 過去分詞（受動態）",
  },
  {
    id: 55,
    type: "part_of_speech",
    question: "We are looking for a highly ______ candidate.",
    choices: ["motivate", "motivating", "motivated", "motivation"],
    answer: "motivated",
    translation: "私たちは非常に意欲的な候補者を探している",
    comment: "人の状態 → ed",
  },

  {
    id: 56,
    type: "part_of_speech",
    question: "There has been a steady ______ in sales.",
    choices: ["increase", "increasing", "increased", "increasingly"],
    answer: "increase",
    translation: "売上は着実に増加している",
    comment: "a + 形容詞の後 → 名詞",
  },
  {
    id: 57,
    type: "part_of_speech",
    question: "She spoke ______ during the meeting.",
    choices: ["confidence", "confident", "confidently", "confidential"],
    answer: "confidently",
    translation: "彼女は会議中自信を持って話した",
    comment: "動詞 spoke を修飾 → 副詞",
  },
  {
    id: 58,
    type: "part_of_speech",
    question: "The manager expressed his ______ about the issue.",
    choices: ["concern", "concerned", "concerning", "concerns"],
    answer: "concern",
    translation: "マネージャーはその問題について懸念を示した",
    comment: "his の後は名詞",
  },
  {
    id: 59,
    type: "part_of_speech",
    question: "The report provides ______ information.",
    choices: ["value", "valuable", "valuably", "valuation"],
    answer: "valuable",
    translation: "その報告書は有益な情報を提供する",
    comment: "名詞 information を修飾 → 形容詞",
  },
  {
    id: 60,
    type: "part_of_speech",
    question: "The task was completed ______.",
    choices: ["success", "successful", "successfully", "succeed"],
    answer: "successfully",
    translation: "その作業は無事に完了した",
    comment: "動詞を修飾 → 副詞",
  },

  {
    id: 61,
    type: "part_of_speech",
    question: "She has experience in project ______.",
    choices: ["manage", "manager", "management", "manageable"],
    answer: "management",
    translation: "彼女はプロジェクト管理の経験がある",
    comment: "in の後は名詞",
  },
  {
    id: 62,
    type: "part_of_speech",
    question: "The CEO made a very ______ decision.",
    choices: ["controversy", "controversial", "controversially", "controvert"],
    answer: "controversial",
    translation: "CEOは非常に物議を醸す決定をした",
    comment: "decision を修飾 → 形容詞",
  },
  {
    id: 63,
    type: "part_of_speech",
    question: "The results were quite ______.",
    choices: ["impress", "impressed", "impressive", "impression"],
    answer: "impressive",
    translation: "結果は非常に印象的だった",
    comment: "be動詞の後 → 形容詞",
  },
  {
    id: 64,
    type: "part_of_speech",
    question: "We appreciate your prompt ______.",
    choices: ["respond", "response", "responsive", "responding"],
    answer: "response",
    translation: "迅速な対応に感謝します",
    comment: "your の後 → 名詞",
  },
  {
    id: 65,
    type: "part_of_speech",
    question: "The company seeks employees with strong communication ______.",
    choices: ["skill", "skills", "skilled", "skillful"],
    answer: "skills",
    translation:
      "その会社は優れたコミュニケーション能力を持つ従業員を求めている",
    comment: "能力系は複数形が自然",
  },

  {
    id: 66,
    type: "part_of_speech",
    question: "The sudden ______ of the flight caused confusion.",
    choices: ["cancel", "cancellation", "canceled", "canceling"],
    answer: "cancellation",
    translation: "突然のフライトのキャンセルが混乱を引き起こした",
    comment: "the + 名詞",
  },
  {
    id: 67,
    type: "part_of_speech",
    question: "The instructions were ______ written.",
    choices: ["clear", "clearly", "clarity", "clearing"],
    answer: "clearly",
    translation: "指示は明確に書かれていた",
    comment: "written を修飾 → 副詞",
  },
  {
    id: 68,
    type: "part_of_speech",
    question: "There is a strong ______ that sales will rise.",
    choices: ["likely", "likelihood", "liken", "alike"],
    answer: "likelihood",
    translation: "売上が上がる可能性が高い",
    comment: "a + 形容詞の後 → 名詞",
  },
  {
    id: 69,
    type: "part_of_speech",
    question: "The new system will ______ efficiency.",
    choices: ["improvement", "improve", "improving", "improved"],
    answer: "improve",
    translation: "新しいシステムは効率を改善するだろう",
    comment: "will の後 → 動詞原形",
  },
  {
    id: 70,
    type: "part_of_speech",
    question: "The company faced serious ______ problems.",
    choices: ["finance", "financial", "financially", "financing"],
    answer: "financial",
    translation: "会社は深刻な財政問題に直面した",
    comment: "名詞を修飾 → 形容詞",
  },
  {
    id: 71,
    type: "part_of_speech",
    question: "The manager announced the ______ of a new policy.",
    choices: ["introduce", "introduction", "introducing", "introduced"],
    answer: "introduction",
    translation: "マネージャーは新しい方針の導入を発表した",
    comment: "the + 名詞、of が来たら動作名詞",
  },
  {
    id: 72,
    type: "part_of_speech",
    question: "The task must be completed ______.",
    choices: ["quick", "quickly", "quickness", "quicken"],
    answer: "quickly",
    translation: "その作業は迅速に完了されなければならない",
    comment: "動詞を修飾 → 副詞",
  },
  {
    id: 73,
    type: "part_of_speech",
    question: "The company provided ______ support.",
    choices: ["help", "helpful", "helpfully", "helpfulness"],
    answer: "helpful",
    translation: "その会社は有益な支援を提供した",
    comment: "名詞を修飾 → 形容詞",
  },
  {
    id: 74,
    type: "part_of_speech",
    question: "The system will ______ performance.",
    choices: ["improvement", "improving", "improve", "improved"],
    answer: "improve",
    translation: "そのシステムは性能を向上させるだろう",
    comment: "will の後 → 動詞原形",
  },
  {
    id: 75,
    type: "part_of_speech",
    question: "There was a sudden ______ in demand.",
    choices: ["increase", "increasing", "increased", "increasingly"],
    answer: "increase",
    translation: "需要が突然増加した",
    comment: "a + 形容詞 + 名詞",
  },

  {
    id: 76,
    type: "part_of_speech",
    question: "The instructions are easy to ______.",
    choices: ["understand", "understanding", "understood", "understands"],
    answer: "understand",
    translation: "その指示は理解しやすい",
    comment: "easy to + 動詞原形",
  },
  {
    id: 77,
    type: "part_of_speech",
    question: "We appreciate your kind ______.",
    choices: ["assist", "assistance", "assisting", "assistant"],
    answer: "assistance",
    translation: "ご親切なご支援に感謝します",
    comment: "your の後 → 名詞",
  },
  {
    id: 78,
    type: "part_of_speech",
    question: "She handled the situation very ______.",
    choices: [
      "professional",
      "professionally",
      "profession",
      "professionalism",
    ],
    answer: "professionally",
    translation: "彼女はその状況を非常に専門的に対処した",
    comment: "動詞を修飾 → 副詞",
  },
  {
    id: 79,
    type: "part_of_speech",
    question: "The results were highly ______.",
    choices: ["succeed", "success", "successful", "successfully"],
    answer: "successful",
    translation: "結果は非常に成功していた",
    comment: "be動詞の後 → 形容詞",
  },
  {
    id: 80,
    type: "part_of_speech",
    question:
      "The company is seeking candidates with strong leadership ______.",
    choices: ["skill", "skills", "skilled", "skillful"],
    answer: "skills",
    translation: "その会社は強いリーダーシップ能力を持つ候補者を探している",
    comment: "能力系は複数形",
  },

  {
    id: 81,
    type: "part_of_speech",
    question: "The new policy will ______ productivity.",
    choices: ["increase", "increasing", "increased", "increasingly"],
    answer: "increase",
    translation: "新しい方針は生産性を向上させるだろう",
    comment: "will の後 → 動詞原形",
  },
  {
    id: 82,
    type: "part_of_speech",
    question: "The manager made a very ______ comment.",
    choices: ["use", "useful", "usefully", "usefulness"],
    answer: "useful",
    translation: "マネージャーは非常に有益なコメントをした",
    comment: "名詞を修飾 → 形容詞",
  },
  {
    id: 83,
    type: "part_of_speech",
    question: "The issue was carefully ______.",
    choices: ["analyze", "analysis", "analyzed", "analyzing"],
    answer: "analyzed",
    translation: "その問題は注意深く分析された",
    comment: "be + 過去分詞",
  },
  {
    id: 84,
    type: "part_of_speech",
    question: "There is a high ______ of success.",
    choices: ["likely", "likelihood", "liken", "alike"],
    answer: "likelihood",
    translation: "成功する可能性が高い",
    comment: "a + 形容詞の後 → 名詞",
  },
  {
    id: 85,
    type: "part_of_speech",
    question: "The meeting was very ______.",
    choices: ["interest", "interesting", "interested", "interestingly"],
    answer: "interesting",
    translation: "会議はとても興味深かった",
    comment: "モノ → ing",
  },

  {
    id: 86,
    type: "part_of_speech",
    question: "The company made an important ______.",
    choices: ["decide", "decision", "deciding", "decisive"],
    answer: "decision",
    translation: "会社は重要な決定を下した",
    comment: "a + 形容詞 + 名詞",
  },
  {
    id: 87,
    type: "part_of_speech",
    question: "The work was completed ______.",
    choices: ["perfect", "perfectly", "perfection", "perfecting"],
    answer: "perfectly",
    translation: "作業は完璧に完了した",
    comment: "動詞を修飾",
  },
  {
    id: 88,
    type: "part_of_speech",
    question:
      "The manager is responsible for the ______ operation of the system.",
    choices: ["smooth", "smoothly", "smoothness", "smoothing"],
    answer: "smooth",
    translation: "マネージャーはシステムの円滑な運用に責任がある",
    comment: "名詞を修飾",
  },
  {
    id: 89,
    type: "part_of_speech",
    question: "We are satisfied with the ______ of the product.",
    choices: ["perform", "performance", "performing", "performed"],
    answer: "performance",
    translation: "私たちは製品の性能に満足している",
    comment: "the + 名詞",
  },
  {
    id: 90,
    type: "part_of_speech",
    question: "The company plans to ______ its services.",
    choices: ["expand", "expansion", "expanding", "expanded"],
    answer: "expand",
    translation: "その会社はサービスを拡大する予定だ",
    comment: "to の後 → 動詞原形",
  },

  {
    id: 91,
    type: "part_of_speech",
    question: "The results were quite ______.",
    choices: ["impress", "impressive", "impressed", "impression"],
    answer: "impressive",
    translation: "結果はかなり印象的だった",
    comment: "be動詞の後 → 形容詞",
  },
  {
    id: 92,
    type: "part_of_speech",
    question: "She spoke ______ about the issue.",
    choices: ["clear", "clearly", "clarity", "clearing"],
    answer: "clearly",
    translation: "彼女はその問題について明確に話した",
    comment: "動詞を修飾",
  },
  {
    id: 93,
    type: "part_of_speech",
    question: "The sudden ______ surprised everyone.",
    choices: ["announce", "announcement", "announcing", "announced"],
    answer: "announcement",
    translation: "突然の発表が皆を驚かせた",
    comment: "the + 名詞",
  },
  {
    id: 94,
    type: "part_of_speech",
    question: "The company is facing serious ______ problems.",
    choices: ["finance", "financial", "financially", "financing"],
    answer: "financial",
    translation: "会社は深刻な財政問題に直面している",
    comment: "名詞を修飾",
  },
  {
    id: 95,
    type: "part_of_speech",
    question: "The report was written very ______.",
    choices: ["careful", "carefully", "care", "caring"],
    answer: "carefully",
    translation: "報告書は非常に注意深く書かれた",
    comment: "動詞を修飾",
  },

  {
    id: 96,
    type: "part_of_speech",
    question: "The company showed great ______ in its performance.",
    choices: ["improve", "improvement", "improving", "improved"],
    answer: "improvement",
    translation: "会社は業績に大きな改善を見せた",
    comment: "形容詞の後 → 名詞",
  },
  {
    id: 97,
    type: "part_of_speech",
    question: "The presentation was very ______.",
    choices: ["interest", "interesting", "interested", "interestingly"],
    answer: "interesting",
    translation: "プレゼンはとても興味深かった",
    comment: "モノ → ing",
  },
  {
    id: 98,
    type: "part_of_speech",
    question: "Employees must act ______ in emergencies.",
    choices: ["quick", "quickly", "quickness", "quicken"],
    answer: "quickly",
    translation: "従業員は緊急時に迅速に行動しなければならない",
    comment: "動詞を修飾",
  },
  {
    id: 99,
    type: "part_of_speech",
    question: "The manager gave a detailed ______ of the plan.",
    choices: ["explain", "explanation", "explaining", "explained"],
    answer: "explanation",
    translation: "マネージャーは計画の詳細な説明をした",
    comment: "a + 形容詞 + 名詞",
  },
  {
    id: 100,
    type: "part_of_speech",
    question: "The company is looking for ______ employees.",
    choices: ["skill", "skilled", "skillfully", "skillfulness"],
    answer: "skilled",
    translation: "その会社は熟練した従業員を探している",
    comment: "名詞を修飾 → 形容詞",
  },
  {
    id: 101,
    type: "part_of_speech",
    question: "The company announced the ______ of a new product.",
    choices: ["launch", "launching", "launched", "launches"],
    answer: "launch",
    translation: "その会社は新製品の発売を発表した",
    comment: "the + 名詞",
  },
  {
    id: 102,
    type: "part_of_speech",
    question: "The task was completed ______ despite difficulties.",
    choices: ["success", "successful", "successfully", "succeed"],
    answer: "successfully",
    translation: "困難にもかかわらず作業は成功裏に完了した",
    comment: "動詞 completed を修飾 → 副詞",
  },
  {
    id: 103,
    type: "part_of_speech",
    question: "The manager gave a very ______ response.",
    choices: ["help", "helpful", "helpfully", "helpfulness"],
    answer: "helpful",
    translation: "マネージャーは非常に役立つ返答をした",
    comment: "名詞 response を修飾",
  },
  {
    id: 104,
    type: "part_of_speech",
    question: "The company plans to ______ its services next year.",
    choices: ["expand", "expansion", "expanding", "expanded"],
    answer: "expand",
    translation: "その会社は来年サービスを拡大する予定だ",
    comment: "to の後 → 動詞原形",
  },
  {
    id: 105,
    type: "part_of_speech",
    question: "The results were quite ______.",
    choices: ["satisfy", "satisfied", "satisfactory", "satisfactorily"],
    answer: "satisfactory",
    translation: "結果はかなり満足のいくものだった",
    comment: "be動詞の後 → 形容詞",
  },

  {
    id: 106,
    type: "part_of_speech",
    question: "There has been a rapid ______ in demand.",
    choices: ["grow", "growth", "growing", "grown"],
    answer: "growth",
    translation: "需要が急速に増加している",
    comment: "a + 形容詞 + 名詞",
  },
  {
    id: 107,
    type: "part_of_speech",
    question: "Employees must act ______ in emergencies.",
    choices: ["quick", "quickly", "quickness", "quicken"],
    answer: "quickly",
    translation: "従業員は緊急時に迅速に行動しなければならない",
    comment: "動詞 act を修飾",
  },
  {
    id: 108,
    type: "part_of_speech",
    question: "The company faces serious ______ issues.",
    choices: ["finance", "financial", "financially", "financing"],
    answer: "financial",
    translation: "会社は深刻な財務問題に直面している",
    comment: "名詞を修飾",
  },
  {
    id: 109,
    type: "part_of_speech",
    question: "We appreciate your prompt ______.",
    choices: ["respond", "response", "responsive", "responding"],
    answer: "response",
    translation: "迅速な対応に感謝します",
    comment: "your の後 → 名詞",
  },
  {
    id: 110,
    type: "part_of_speech",
    question: "The new system will ______ efficiency.",
    choices: ["improve", "improvement", "improving", "improved"],
    answer: "improve",
    translation: "新システムは効率を向上させるだろう",
    comment: "will の後 → 動詞原形",
  },

  {
    id: 111,
    type: "part_of_speech",
    question: "The presentation was very ______.",
    choices: ["interest", "interesting", "interested", "interestingly"],
    answer: "interesting",
    translation: "プレゼンはとても興味深かった",
    comment: "モノの性質 → ing",
  },
  {
    id: 112,
    type: "part_of_speech",
    question: "The manager made an important ______.",
    choices: ["decide", "decision", "deciding", "decisive"],
    answer: "decision",
    translation: "マネージャーは重要な決定をした",
    comment: "a + 形容詞 + 名詞",
  },
  {
    id: 113,
    type: "part_of_speech",
    question: "The issue was handled very ______.",
    choices: ["careful", "carefully", "care", "caring"],
    answer: "carefully",
    translation: "問題は非常に慎重に扱われた",
    comment: "動詞を修飾",
  },
  {
    id: 114,
    type: "part_of_speech",
    question: "There is little ______ that the plan will fail.",
    choices: ["doubt", "doubtful", "doubting", "doubted"],
    answer: "doubt",
    translation: "その計画が失敗する可能性はほとんどない",
    comment: "little + 名詞",
  },
  {
    id: 115,
    type: "part_of_speech",
    question: "The instructions were easy to ______.",
    choices: ["follow", "following", "followed", "follows"],
    answer: "follow",
    translation: "その指示は従いやすかった",
    comment: "to の後 → 動詞原形",
  },

  {
    id: 116,
    type: "part_of_speech",
    question: "The company showed significant ______.",
    choices: ["grow", "growth", "growing", "grown"],
    answer: "growth",
    translation: "会社は著しい成長を見せた",
    comment: "形容詞の後 → 名詞",
  },
  {
    id: 117,
    type: "part_of_speech",
    question: "The report was written ______.",
    choices: ["clear", "clearly", "clarity", "clearing"],
    answer: "clearly",
    translation: "報告書は明確に書かれていた",
    comment: "動詞を修飾",
  },
  {
    id: 118,
    type: "part_of_speech",
    question: "The company is seeking ______ candidates.",
    choices: ["experience", "experienced", "experiencefully", "experiencing"],
    answer: "experienced",
    translation: "会社は経験豊富な候補者を探している",
    comment: "人の状態 → ed",
  },
  {
    id: 119,
    type: "part_of_speech",
    question: "The sudden ______ caused confusion.",
    choices: ["cancel", "cancellation", "canceling", "canceled"],
    answer: "cancellation",
    translation: "突然のキャンセルが混乱を引き起こした",
    comment: "the + 名詞",
  },
  {
    id: 120,
    type: "part_of_speech",
    question: "The company aims to ______ its market share.",
    choices: ["increase", "increasing", "increased", "increasingly"],
    answer: "increase",
    translation: "会社は市場シェアを拡大することを目指している",
    comment: "to の後 → 動詞原形",
  },

  {
    id: 121,
    type: "part_of_speech",
    question: "The results were extremely ______.",
    choices: ["impress", "impressive", "impressed", "impression"],
    answer: "impressive",
    translation: "結果は非常に印象的だった",
    comment: "be動詞の後 → 形容詞",
  },
  {
    id: 122,
    type: "part_of_speech",
    question: "Employees must respond ______ to emails.",
    choices: ["quick", "quickly", "quickness", "quicken"],
    answer: "quickly",
    translation: "従業員はメールに迅速に対応しなければならない",
    comment: "動詞を修飾",
  },
  {
    id: 123,
    type: "part_of_speech",
    question: "The company is known for its high ______.",
    choices: ["quality", "qualify", "qualified", "qualifying"],
    answer: "quality",
    translation: "その会社は高品質で知られている",
    comment: "its の後 → 名詞",
  },
  {
    id: 124,
    type: "part_of_speech",
    question: "The manager gave a highly ______ speech.",
    choices: ["motivate", "motivating", "motivated", "motivation"],
    answer: "motivating",
    translation: "マネージャーは非常にやる気を起こさせるスピーチをした",
    comment: "モノ → ing",
  },
  {
    id: 125,
    type: "part_of_speech",
    question: "There has been a noticeable ______.",
    choices: ["improve", "improvement", "improving", "improved"],
    answer: "improvement",
    translation: "顕著な改善があった",
    comment: "a の後 → 名詞",
  },

  {
    id: 126,
    type: "part_of_speech",
    question: "The task was ______ completed.",
    choices: ["quick", "quickly", "quickness", "quicken"],
    answer: "quickly",
    translation: "作業は迅速に完了した",
    comment: "completed を修飾",
  },
  {
    id: 127,
    type: "part_of_speech",
    question: "The company is facing ______ competition.",
    choices: ["intense", "intensely", "intensity", "intensify"],
    answer: "intense",
    translation: "会社は激しい競争に直面している",
    comment: "名詞を修飾",
  },
  {
    id: 128,
    type: "part_of_speech",
    question: "The manager provided a clear ______.",
    choices: ["explain", "explanation", "explaining", "explained"],
    answer: "explanation",
    translation: "マネージャーは明確な説明をした",
    comment: "a + 形容詞 + 名詞",
  },
  {
    id: 129,
    type: "part_of_speech",
    question: "The company will ______ new employees.",
    choices: ["hire", "hiring", "hired", "hires"],
    answer: "hire",
    translation: "会社は新しい従業員を雇うだろう",
    comment: "will の後 → 動詞原形",
  },
  {
    id: 130,
    type: "part_of_speech",
    question: "The results were quite ______.",
    choices: ["surprise", "surprising", "surprised", "surprisingly"],
    answer: "surprising",
    translation: "結果はかなり驚くべきものだった",
    comment: "モノ → ing",
  },

  {
    id: 131,
    type: "part_of_speech",
    question: "The company showed great ______ in sales.",
    choices: ["increase", "increasing", "increased", "increasingly"],
    answer: "increase",
    translation: "会社は売上の大きな増加を示した",
    comment: "great の後 → 名詞",
  },
  {
    id: 132,
    type: "part_of_speech",
    question: "The issue was ______ resolved.",
    choices: ["quick", "quickly", "quickness", "quicken"],
    answer: "quickly",
    translation: "問題は迅速に解決された",
    comment: "動詞を修飾",
  },
  {
    id: 133,
    type: "part_of_speech",
    question: "The manager is a highly ______ individual.",
    choices: ["motivate", "motivated", "motivating", "motivation"],
    answer: "motivated",
    translation: "マネージャーは非常に意欲的な人物だ",
    comment: "人 → ed",
  },
  {
    id: 134,
    type: "part_of_speech",
    question: "The company made a significant ______.",
    choices: ["expand", "expansion", "expanding", "expanded"],
    answer: "expansion",
    translation: "会社は大きな拡大を行った",
    comment: "a + 形容詞 + 名詞",
  },
  {
    id: 135,
    type: "part_of_speech",
    question: "The system will ______ data automatically.",
    choices: ["process", "processing", "processed", "processes"],
    answer: "process",
    translation: "システムは自動的にデータを処理する",
    comment: "will の後 → 動詞原形",
  },

  {
    id: 136,
    type: "part_of_speech",
    question: "The presentation was very ______.",
    choices: ["confuse", "confusing", "confused", "confusion"],
    answer: "confusing",
    translation: "プレゼンはとても分かりにくかった",
    comment: "モノ → ing",
  },
  {
    id: 137,
    type: "part_of_speech",
    question: "Employees must work ______ to meet deadlines.",
    choices: ["hard", "hardly", "hardness", "harden"],
    answer: "hard",
    translation: "従業員は締め切りに間に合うよう一生懸命働かなければならない",
    comment: "hard = 副詞（-lyでない例）",
  },
  {
    id: 138,
    type: "part_of_speech",
    question: "There is a growing ______ for skilled workers.",
    choices: ["demand", "demanding", "demanded", "demands"],
    answer: "demand",
    translation: "熟練労働者の需要が高まっている",
    comment: "a + 形容詞 + 名詞",
  },
  {
    id: 139,
    type: "part_of_speech",
    question: "The company plans to ______ its operations.",
    choices: ["expand", "expansion", "expanding", "expanded"],
    answer: "expand",
    translation: "会社は事業を拡大する予定だ",
    comment: "to の後 → 動詞原形",
  },
  {
    id: 140,
    type: "part_of_speech",
    question: "The results were extremely ______.",
    choices: ["satisfy", "satisfied", "satisfying", "satisfaction"],
    answer: "satisfying",
    translation: "結果は非常に満足のいくものだった",
    comment: "モノ → ing",
  },

  {
    id: 141,
    type: "part_of_speech",
    question: "The company showed steady ______.",
    choices: ["grow", "growth", "growing", "grown"],
    answer: "growth",
    translation: "会社は安定した成長を見せた",
    comment: "形容詞の後 → 名詞",
  },
  {
    id: 142,
    type: "part_of_speech",
    question: "The report was written ______.",
    choices: ["clear", "clearly", "clarity", "clearing"],
    answer: "clearly",
    translation: "報告書は明確に書かれていた",
    comment: "動詞を修飾",
  },
  {
    id: 143,
    type: "part_of_speech",
    question: "The manager gave a ______ explanation.",
    choices: ["detail", "detailed", "detailly", "detailing"],
    answer: "detailed",
    translation: "マネージャーは詳細な説明をした",
    comment: "名詞を修飾",
  },
  {
    id: 144,
    type: "part_of_speech",
    question: "The sudden ______ surprised everyone.",
    choices: ["arrive", "arrival", "arriving", "arrived"],
    answer: "arrival",
    translation: "突然の到着が皆を驚かせた",
    comment: "the + 名詞",
  },
  {
    id: 145,
    type: "part_of_speech",
    question: "The system will ______ errors automatically.",
    choices: ["detect", "detection", "detecting", "detected"],
    answer: "detect",
    translation: "システムは自動的にエラーを検出する",
    comment: "will の後 → 動詞原形",
  },

  {
    id: 146,
    type: "part_of_speech",
    question: "The movie was very ______.",
    choices: ["interest", "interesting", "interested", "interestingly"],
    answer: "interesting",
    translation: "その映画はとても面白かった",
    comment: "モノ → ing",
  },
  {
    id: 147,
    type: "part_of_speech",
    question: "Employees must respond ______ to requests.",
    choices: ["prompt", "promptly", "promptness", "prompting"],
    answer: "promptly",
    translation: "従業員は要請に迅速に対応しなければならない",
    comment: "動詞を修飾",
  },
  {
    id: 148,
    type: "part_of_speech",
    question: "The company made an important ______.",
    choices: ["decide", "decision", "deciding", "decisive"],
    answer: "decision",
    translation: "会社は重要な決定を下した",
    comment: "a + 形容詞 + 名詞",
  },
  {
    id: 149,
    type: "part_of_speech",
    question: "The manager is a highly ______ person.",
    choices: ["motivate", "motivated", "motivating", "motivation"],
    answer: "motivated",
    translation: "マネージャーは非常に意欲的な人物だ",
    comment: "人 → ed",
  },
  {
    id: 150,
    type: "part_of_speech",
    question: "There has been a noticeable ______ in performance.",
    choices: ["improve", "improvement", "improving", "improved"],
    answer: "improvement",
    translation: "業績に顕著な改善があった",
    comment: "a + 形容詞 + 名詞",
  },
    {
    id: 151,
    type: "vocabulary",
    question: "The company plans to ______ its market share next year.",
    choices: ["increase", "reduce", "maintain", "delay"],
    answer: "increase",
    translation: "会社は来年市場シェアを拡大する予定だ",
    comment: "increase:増やす / reduce:減らす / maintain:維持する / delay:遅らせる → 文脈は拡大"
  },
  {
    id: 152,
    type: "vocabulary",
    question: "The manager decided to ______ the meeting due to an emergency.",
    choices: ["postpone", "attend", "approve", "conduct"],
    answer: "postpone",
    translation: "マネージャーは緊急事態のため会議を延期することにした",
    comment: "postpone:延期する / attend:出席する / approve:承認する / conduct:実施する → 緊急→延期"
  },
  {
    id: 153,
    type: "vocabulary",
    question: "The new policy will ______ employees to work more efficiently.",
    choices: ["encourage", "refuse", "ignore", "prevent"],
    answer: "encourage",
    translation: "新しい方針は従業員がより効率的に働くことを促すだろう",
    comment: "encourage:促す / refuse:拒否する / ignore:無視する / prevent:妨げる → ポジティブ文脈"
  },
  {
    id: 154,
    type: "vocabulary",
    question: "The company must ______ customer complaints quickly.",
    choices: ["handle", "avoid", "forget", "miss"],
    answer: "handle",
    translation: "会社は顧客の苦情に迅速に対応しなければならない",
    comment: "handle:対応する / avoid:避ける / forget:忘れる / miss:見逃す → 苦情→対応"
  },
  {
    id: 155,
    type: "vocabulary",
    question: "The report provides ______ information about the market.",
    choices: ["accurate", "expensive", "slow", "rare"],
    answer: "accurate",
    translation: "その報告書は市場について正確な情報を提供する",
    comment: "accurate:正確な / expensive:高価な / slow:遅い / rare:珍しい → 情報→正確"
  },

  {
    id: 156,
    type: "vocabulary",
    question: "The company aims to ______ costs in order to increase profits.",
    choices: ["reduce", "increase", "ignore", "create"],
    answer: "reduce",
    translation: "会社は利益を増やすためコストを削減することを目指している",
    comment: "reduce:減らす / increase:増やす / ignore:無視する / create:作る → 利益↑ならコスト↓"
  },
  {
    id: 157,
    type: "vocabulary",
    question: "Employees are required to ______ safety regulations.",
    choices: ["follow", "break", "change", "forget"],
    answer: "follow",
    translation: "従業員は安全規則に従う必要がある",
    comment: "follow:従う / break:破る / change:変える / forget:忘れる → 規則→従う"
  },
  {
    id: 158,
    type: "vocabulary",
    question: "The company will ______ a new product next month.",
    choices: ["launch", "cancel", "repair", "replace"],
    answer: "launch",
    translation: "会社は来月新製品を発売する予定だ",
    comment: "launch:発売する / cancel:中止する / repair:修理する / replace:交換する → 製品→発売"
  },
  {
    id: 159,
    type: "vocabulary",
    question: "The manager will ______ the proposal before making a decision.",
    choices: ["review", "ignore", "reject", "skip"],
    answer: "review",
    translation: "マネージャーは決定を下す前に提案を見直すだろう",
    comment: "review:見直す / ignore:無視する / reject:却下する / skip:飛ばす → 決定前→確認"
  },
  {
    id: 160,
    type: "vocabulary",
    question: "The company is trying to ______ its services.",
    choices: ["improve", "damage", "destroy", "delay"],
    answer: "improve",
    translation: "会社はサービスの改善を試みている",
    comment: "improve:改善する / damage:損なう / destroy:破壊する / delay:遅らせる → 文脈ポジ"
  },

  {
    id: 161,
    type: "vocabulary",
    question: "The employee was ______ for his hard work.",
    choices: ["praised", "punished", "ignored", "avoided"],
    answer: "praised",
    translation: "その従業員は努力を称賛された",
    comment: "praised:褒められた / punished:罰された / ignored:無視された / avoided:避けられた"
  },
  {
    id: 162,
    type: "vocabulary",
    question: "The company needs to ______ more customers.",
    choices: ["attract", "lose", "ignore", "refuse"],
    answer: "attract",
    translation: "会社はより多くの顧客を引きつける必要がある",
    comment: "attract:引きつける / lose:失う / ignore:無視 / refuse:拒否"
  },
  {
    id: 163,
    type: "vocabulary",
    question: "The project was ______ due to lack of funding.",
    choices: ["cancelled", "continued", "approved", "started"],
    answer: "cancelled",
    translation: "資金不足のためプロジェクトは中止された",
    comment: "cancelled:中止 / continued:継続 / approved:承認 / started:開始"
  },
  {
    id: 164,
    type: "vocabulary",
    question: "The company will ______ a new strategy soon.",
    choices: ["adopt", "refuse", "ignore", "forget"],
    answer: "adopt",
    translation: "会社はまもなく新しい戦略を採用するだろう",
    comment: "adopt:採用する / refuse:拒否 / ignore:無視 / forget:忘れる"
  },
  {
    id: 165,
    type: "vocabulary",
    question: "The manager asked employees to ______ the deadline.",
    choices: ["meet", "miss", "delay", "change"],
    answer: "meet",
    translation: "マネージャーは従業員に締め切りを守るよう求めた",
    comment: "meet:守る / miss:逃す / delay:遅らせる / change:変更"
  },

  {
    id: 166,
    type: "vocabulary",
    question: "The company must ______ quality standards.",
    choices: ["maintain", "break", "ignore", "lower"],
    answer: "maintain",
    translation: "会社は品質基準を維持しなければならない",
    comment: "maintain:維持 / break:破る / ignore:無視 / lower:下げる"
  },
  {
    id: 167,
    type: "vocabulary",
    question: "The manager decided to ______ the plan.",
    choices: ["approve", "reject", "ignore", "delay"],
    answer: "approve",
    translation: "マネージャーは計画を承認することにした",
    comment: "approve:承認 / reject:却下 / ignore:無視 / delay:延期"
  },
  {
    id: 168,
    type: "vocabulary",
    question: "The company is trying to ______ its reputation.",
    choices: ["improve", "damage", "ignore", "forget"],
    answer: "improve",
    translation: "会社は評判を改善しようとしている",
    comment: "improve:改善 / damage:傷つける / ignore:無視 / forget:忘れる"
  },
  {
    id: 169,
    type: "vocabulary",
    question: "The report aims to ______ the causes of the problem.",
    choices: ["identify", "hide", "ignore", "forget"],
    answer: "identify",
    translation: "報告書は問題の原因を特定することを目的としている",
    comment: "identify:特定 / hide:隠す / ignore:無視 / forget:忘れる"
  },
  {
    id: 170,
    type: "vocabulary",
    question: "The company will ______ new employees next month.",
    choices: ["hire", "fire", "ignore", "lose"],
    answer: "hire",
    translation: "会社は来月新しい従業員を雇う予定だ",
    comment: "hire:雇う / fire:解雇 / ignore:無視 / lose:失う"
  },
  {
    id: 171,
    type: "vocabulary",
    question: "The company decided to ______ its prices due to rising costs.",
    choices: ["raise", "lower", "ignore", "cancel"],
    answer: "raise",
    translation: "コスト上昇のため会社は価格を引き上げることにした",
    comment: "raise:上げる / lower:下げる / ignore:無視 / cancel:中止 → コスト↑→価格↑"
  },
  {
    id: 172,
    type: "vocabulary",
    question: "The manager asked the team to ______ the report by Friday.",
    choices: ["complete", "delay", "ignore", "forget"],
    answer: "complete",
    translation: "マネージャーはチームに金曜までに報告書を完成させるよう求めた",
    comment: "complete:完成 / delay:遅らせる / ignore:無視 / forget:忘れる"
  },
  {
    id: 173,
    type: "vocabulary",
    question: "The company will ______ a new office in Tokyo.",
    choices: ["open", "close", "ignore", "cancel"],
    answer: "open",
    translation: "会社は東京に新しいオフィスを開設する予定だ",
    comment: "open:開く / close:閉じる / ignore:無視 / cancel:中止"
  },
  {
    id: 174,
    type: "vocabulary",
    question: "The employee failed to ______ the deadline.",
    choices: ["meet", "create", "follow", "build"],
    answer: "meet",
    translation: "その従業員は締め切りを守れなかった",
    comment: "meet:守る / create:作る / follow:従う / build:建てる"
  },
  {
    id: 175,
    type: "vocabulary",
    question: "The company plans to ______ its production next year.",
    choices: ["increase", "decrease", "ignore", "stop"],
    answer: "increase",
    translation: "会社は来年生産を増やす予定だ",
    comment: "increase:増やす / decrease:減らす / ignore:無視 / stop:止める"
  },

  {
    id: 176,
    type: "vocabulary",
    question: "The manager will ______ the final decision.",
    choices: ["make", "break", "ignore", "forget"],
    answer: "make",
    translation: "マネージャーが最終決定を下すだろう",
    comment: "make:行う / break:壊す / ignore:無視 / forget:忘れる → make a decision"
  },
  {
    id: 177,
    type: "vocabulary",
    question: "The company needs to ______ customer satisfaction.",
    choices: ["improve", "damage", "ignore", "reduce"],
    answer: "improve",
    translation: "会社は顧客満足度を改善する必要がある",
    comment: "improve:改善 / damage:損なう / ignore:無視 / reduce:減らす"
  },
  {
    id: 178,
    type: "vocabulary",
    question: "The report will ______ the main issues.",
    choices: ["highlight", "hide", "ignore", "forget"],
    answer: "highlight",
    translation: "報告書は主な問題を強調するだろう",
    comment: "highlight:強調 / hide:隠す / ignore:無視 / forget:忘れる"
  },
  {
    id: 179,
    type: "vocabulary",
    question: "The company is trying to ______ new markets.",
    choices: ["enter", "leave", "ignore", "avoid"],
    answer: "enter",
    translation: "会社は新しい市場に参入しようとしている",
    comment: "enter:参入 / leave:離れる / ignore:無視 / avoid:避ける"
  },
  {
    id: 180,
    type: "vocabulary",
    question: "The manager asked him to ______ the problem quickly.",
    choices: ["solve", "create", "ignore", "forget"],
    answer: "solve",
    translation: "マネージャーは彼に問題をすぐ解決するよう求めた",
    comment: "solve:解決 / create:作る / ignore:無視 / forget:忘れる"
  },

  {
    id: 181,
    type: "vocabulary",
    question: "The company will ______ a new system next year.",
    choices: ["introduce", "remove", "ignore", "delay"],
    answer: "introduce",
    translation: "会社は来年新しいシステムを導入する予定だ",
    comment: "introduce:導入 / remove:取り除く / ignore:無視 / delay:遅らせる"
  },
  {
    id: 182,
    type: "vocabulary",
    question: "The employee was asked to ______ the document.",
    choices: ["submit", "ignore", "destroy", "forget"],
    answer: "submit",
    translation: "その従業員は書類を提出するよう求められた",
    comment: "submit:提出 / ignore:無視 / destroy:破壊 / forget:忘れる"
  },
  {
    id: 183,
    type: "vocabulary",
    question: "The company aims to ______ its profits.",
    choices: ["increase", "decrease", "lose", "ignore"],
    answer: "increase",
    translation: "会社は利益を増やすことを目指している",
    comment: "increase:増やす / decrease:減らす / lose:失う / ignore:無視"
  },
  {
    id: 184,
    type: "vocabulary",
    question: "The manager decided to ______ the proposal.",
    choices: ["accept", "reject", "ignore", "forget"],
    answer: "accept",
    translation: "マネージャーは提案を受け入れることにした",
    comment: "accept:受け入れる / reject:拒否 / ignore:無視 / forget:忘れる"
  },
  {
    id: 185,
    type: "vocabulary",
    question: "The company must ______ its resources efficiently.",
    choices: ["use", "waste", "ignore", "lose"],
    answer: "use",
    translation: "会社は資源を効率的に使わなければならない",
    comment: "use:使う / waste:無駄にする / ignore:無視 / lose:失う"
  },

  {
    id: 186,
    type: "vocabulary",
    question: "The employee was ______ for arriving late.",
    choices: ["warned", "praised", "rewarded", "promoted"],
    answer: "warned",
    translation: "その従業員は遅刻したことで注意された",
    comment: "warned:注意 / praised:称賛 / rewarded:報酬 / promoted:昇進"
  },
  {
    id: 187,
    type: "vocabulary",
    question: "The company will ______ its operations overseas.",
    choices: ["expand", "reduce", "ignore", "stop"],
    answer: "expand",
    translation: "会社は海外での事業を拡大する予定だ",
    comment: "expand:拡大 / reduce:縮小 / ignore:無視 / stop:停止"
  },
  {
    id: 188,
    type: "vocabulary",
    question: "The manager asked the team to ______ the issue.",
    choices: ["discuss", "ignore", "forget", "hide"],
    answer: "discuss",
    translation: "マネージャーはチームにその問題を議論するよう求めた",
    comment: "discuss:議論 / ignore:無視 / forget:忘れる / hide:隠す"
  },
  {
    id: 189,
    type: "vocabulary",
    question: "The company needs to ______ risks.",
    choices: ["reduce", "increase", "ignore", "create"],
    answer: "reduce",
    translation: "会社はリスクを減らす必要がある",
    comment: "reduce:減らす / increase:増やす / ignore:無視 / create:作る"
  },
  {
    id: 190,
    type: "vocabulary",
    question: "The manager will ______ the performance of employees.",
    choices: ["evaluate", "ignore", "destroy", "forget"],
    answer: "evaluate",
    translation: "マネージャーは従業員の業績を評価するだろう",
    comment: "evaluate:評価 / ignore:無視 / destroy:破壊 / forget:忘れる"
  },

  {
    id: 191,
    type: "vocabulary",
    question: "The company plans to ______ its staff.",
    choices: ["increase", "reduce", "ignore", "delay"],
    answer: "increase",
    translation: "会社は従業員数を増やす予定だ",
    comment: "increase:増やす / reduce:減らす / ignore:無視 / delay:遅らせる"
  },
  {
    id: 192,
    type: "vocabulary",
    question: "The employee failed to ______ instructions.",
    choices: ["follow", "create", "ignore", "forget"],
    answer: "follow",
    translation: "その従業員は指示に従えなかった",
    comment: "follow:従う / create:作る / ignore:無視 / forget:忘れる"
  },
  {
    id: 193,
    type: "vocabulary",
    question: "The company will ______ a new branch.",
    choices: ["open", "close", "ignore", "cancel"],
    answer: "open",
    translation: "会社は新しい支店を開設する予定だ",
    comment: "open:開設 / close:閉鎖 / ignore:無視 / cancel:中止"
  },
  {
    id: 194,
    type: "vocabulary",
    question: "The manager asked the team to ______ the report carefully.",
    choices: ["check", "ignore", "forget", "destroy"],
    answer: "check",
    translation: "マネージャーはチームに報告書を注意深く確認するよう求めた",
    comment: "check:確認 / ignore:無視 / forget:忘れる / destroy:破壊"
  },
  {
    id: 195,
    type: "vocabulary",
    question: "The company needs to ______ customer needs.",
    choices: ["understand", "ignore", "forget", "avoid"],
    answer: "understand",
    translation: "会社は顧客のニーズを理解する必要がある",
    comment: "understand:理解 / ignore:無視 / forget:忘れる / avoid:避ける"
  },

  {
    id: 196,
    type: "vocabulary",
    question: "The company will ______ new technology.",
    choices: ["adopt", "reject", "ignore", "forget"],
    answer: "adopt",
    translation: "会社は新しい技術を採用するだろう",
    comment: "adopt:採用 / reject:拒否 / ignore:無視 / forget:忘れる"
  },
  {
    id: 197,
    type: "vocabulary",
    question: "The manager decided to ______ the meeting.",
    choices: ["hold", "cancel", "ignore", "forget"],
    answer: "hold",
    translation: "マネージャーは会議を開くことにした",
    comment: "hold:開催 / cancel:中止 / ignore:無視 / forget:忘れる"
  },
  {
    id: 198,
    type: "vocabulary",
    question: "The company aims to ______ its brand image.",
    choices: ["strengthen", "weaken", "ignore", "forget"],
    answer: "strengthen",
    translation: "会社はブランドイメージを強化することを目指している",
    comment: "strengthen:強化 / weaken:弱める / ignore:無視 / forget:忘れる"
  },
  {
    id: 199,
    type: "vocabulary",
    question: "The employee was asked to ______ the data.",
    choices: ["analyze", "ignore", "forget", "destroy"],
    answer: "analyze",
    translation: "従業員はデータを分析するよう求められた",
    comment: "analyze:分析 / ignore:無視 / forget:忘れる / destroy:破壊"
  },
  {
    id: 200,
    type: "vocabulary",
    question: "The company will ______ its services to meet demand.",
    choices: ["expand", "reduce", "ignore", "stop"],
    answer: "expand",
    translation: "会社は需要に応えるためサービスを拡大するだろう",
    comment: "expand:拡大 / reduce:縮小 / ignore:無視 / stop:停止"
  },
  {
    id: 201,
    type: "vocabulary",
    question: "The company will ______ its services to Asia.",
    choices: ["expand", "reduce", "ignore", "stop"],
    answer: "expand",
    translation: "会社はアジアへサービスを拡大する予定だ",
    comment: "expand:拡大 / reduce:縮小 / ignore:無視 / stop:停止"
  },
  {
    id: 202,
    type: "vocabulary",
    question: "The manager asked employees to ______ the instructions carefully.",
    choices: ["follow", "ignore", "forget", "destroy"],
    answer: "follow",
    translation: "マネージャーは従業員に指示に従うよう求めた",
    comment: "follow:従う / ignore:無視 / forget:忘れる / destroy:破壊"
  },
  {
    id: 203,
    type: "vocabulary",
    question: "The company decided to ______ a new system.",
    choices: ["introduce", "remove", "ignore", "delay"],
    answer: "introduce",
    translation: "会社は新しいシステムを導入することにした",
    comment: "introduce:導入 / remove:削除 / ignore:無視 / delay:遅延"
  },
  {
    id: 204,
    type: "vocabulary",
    question: "The employee was ______ for excellent performance.",
    choices: ["rewarded", "punished", "ignored", "avoided"],
    answer: "rewarded",
    translation: "その従業員は優れた業績で報酬を受けた",
    comment: "rewarded:報酬 / punished:罰 / ignored:無視 / avoided:避ける"
  },
  {
    id: 205,
    type: "vocabulary",
    question: "The company needs to ______ production costs.",
    choices: ["reduce", "increase", "ignore", "create"],
    answer: "reduce",
    translation: "会社は生産コストを削減する必要がある",
    comment: "reduce:減らす / increase:増やす / ignore:無視 / create:作る"
  },

  {
    id: 206,
    type: "vocabulary",
    question: "The manager will ______ the proposal tomorrow.",
    choices: ["review", "ignore", "cancel", "forget"],
    answer: "review",
    translation: "マネージャーは明日提案を見直すだろう",
    comment: "review:確認 / ignore:無視 / cancel:中止 / forget:忘れる"
  },
  {
    id: 207,
    type: "vocabulary",
    question: "The company aims to ______ its competitiveness.",
    choices: ["improve", "damage", "ignore", "reduce"],
    answer: "improve",
    translation: "会社は競争力を向上させることを目指している",
    comment: "improve:改善 / damage:損なう / ignore:無視 / reduce:減らす"
  },
  {
    id: 208,
    type: "vocabulary",
    question: "The report will ______ the main findings.",
    choices: ["summarize", "hide", "ignore", "forget"],
    answer: "summarize",
    translation: "報告書は主な調査結果を要約するだろう",
    comment: "summarize:要約 / hide:隠す / ignore:無視 / forget:忘れる"
  },
  {
    id: 209,
    type: "vocabulary",
    question: "The company is trying to ______ new opportunities.",
    choices: ["explore", "avoid", "ignore", "destroy"],
    answer: "explore",
    translation: "会社は新しい機会を探っている",
    comment: "explore:探る / avoid:避ける / ignore:無視 / destroy:破壊"
  },
  {
    id: 210,
    type: "vocabulary",
    question: "The manager asked the team to ______ the issue immediately.",
    choices: ["resolve", "ignore", "delay", "hide"],
    answer: "resolve",
    translation: "マネージャーはチームに問題をすぐ解決するよう求めた",
    comment: "resolve:解決 / ignore:無視 / delay:遅らせる / hide:隠す"
  },

  {
    id: 211,
    type: "vocabulary",
    question: "The company will ______ new employees next month.",
    choices: ["hire", "fire", "ignore", "lose"],
    answer: "hire",
    translation: "会社は来月新しい従業員を雇う予定だ",
    comment: "hire:雇う / fire:解雇 / ignore:無視 / lose:失う"
  },
  {
    id: 212,
    type: "vocabulary",
    question: "The employee was asked to ______ the document carefully.",
    choices: ["examine", "ignore", "destroy", "forget"],
    answer: "examine",
    translation: "その従業員は文書を注意深く調べるよう求められた",
    comment: "examine:調査 / ignore:無視 / destroy:破壊 / forget:忘れる"
  },
  {
    id: 213,
    type: "vocabulary",
    question: "The company plans to ______ its product line.",
    choices: ["diversify", "reduce", "ignore", "stop"],
    answer: "diversify",
    translation: "会社は製品ラインを多様化する予定だ",
    comment: "diversify:多様化 / reduce:減らす / ignore:無視 / stop:停止"
  },
  {
    id: 214,
    type: "vocabulary",
    question: "The manager decided to ______ the meeting.",
    choices: ["postpone", "hold", "ignore", "forget"],
    answer: "postpone",
    translation: "マネージャーは会議を延期することにした",
    comment: "postpone:延期 / hold:開催 / ignore:無視 / forget:忘れる"
  },
  {
    id: 215,
    type: "vocabulary",
    question: "The company needs to ______ risks carefully.",
    choices: ["manage", "create", "ignore", "increase"],
    answer: "manage",
    translation: "会社はリスクを慎重に管理する必要がある",
    comment: "manage:管理 / create:作る / ignore:無視 / increase:増やす"
  },

  {
    id: 216,
    type: "vocabulary",
    question: "The employee was ______ for his dedication.",
    choices: ["recognized", "ignored", "punished", "delayed"],
    answer: "recognized",
    translation: "その従業員は献身で評価された",
    comment: "recognized:評価 / ignored:無視 / punished:罰 / delayed:遅延"
  },
  {
    id: 217,
    type: "vocabulary",
    question: "The company will ______ its infrastructure.",
    choices: ["upgrade", "reduce", "ignore", "destroy"],
    answer: "upgrade",
    translation: "会社はインフラをアップグレードするだろう",
    comment: "upgrade:改善 / reduce:縮小 / ignore:無視 / destroy:破壊"
  },
  {
    id: 218,
    type: "vocabulary",
    question: "The manager asked the team to ______ ideas.",
    choices: ["generate", "ignore", "forget", "destroy"],
    answer: "generate",
    translation: "マネージャーはチームにアイデアを生み出すよう求めた",
    comment: "generate:生み出す / ignore:無視 / forget:忘れる / destroy:破壊"
  },
  {
    id: 219,
    type: "vocabulary",
    question: "The company aims to ______ efficiency.",
    choices: ["enhance", "reduce", "ignore", "stop"],
    answer: "enhance",
    translation: "会社は効率を高めることを目指している",
    comment: "enhance:高める / reduce:減らす / ignore:無視 / stop:停止"
  },
  {
    id: 220,
    type: "vocabulary",
    question: "The report will ______ future trends.",
    choices: ["predict", "hide", "ignore", "forget"],
    answer: "predict",
    translation: "報告書は将来の傾向を予測するだろう",
    comment: "predict:予測 / hide:隠す / ignore:無視 / forget:忘れる"
  },

  {
    id: 221,
    type: "vocabulary",
    question: "The company decided to ______ the project.",
    choices: ["terminate", "continue", "ignore", "start"],
    answer: "terminate",
    translation: "会社はそのプロジェクトを終了することにした",
    comment: "terminate:終了 / continue:継続 / ignore:無視 / start:開始"
  },
  {
    id: 222,
    type: "vocabulary",
    question: "The manager will ______ the situation closely.",
    choices: ["monitor", "ignore", "forget", "destroy"],
    answer: "monitor",
    translation: "マネージャーは状況を注意深く監視するだろう",
    comment: "monitor:監視 / ignore:無視 / forget:忘れる / destroy:破壊"
  },
  {
    id: 223,
    type: "vocabulary",
    question: "The company needs to ______ customer feedback.",
    choices: ["collect", "ignore", "destroy", "forget"],
    answer: "collect",
    translation: "会社は顧客のフィードバックを集める必要がある",
    comment: "collect:集める / ignore:無視 / destroy:破壊 / forget:忘れる"
  },
  {
    id: 224,
    type: "vocabulary",
    question: "The employee was asked to ______ the results.",
    choices: ["analyze", "ignore", "destroy", "forget"],
    answer: "analyze",
    translation: "その従業員は結果を分析するよう求められた",
    comment: "analyze:分析 / ignore:無視 / destroy:破壊 / forget:忘れる"
  },
  {
    id: 225,
    type: "vocabulary",
    question: "The company will ______ its brand image.",
    choices: ["strengthen", "weaken", "ignore", "forget"],
    answer: "strengthen",
    translation: "会社はブランドイメージを強化するだろう",
    comment: "strengthen:強化 / weaken:弱化 / ignore:無視 / forget:忘れる"
  },

  {
    id: 226,
    type: "vocabulary",
    question: "The manager asked employees to ______ the task.",
    choices: ["complete", "ignore", "delay", "forget"],
    answer: "complete",
    translation: "マネージャーは従業員にタスクを完了するよう求めた",
    comment: "complete:完了 / ignore:無視 / delay:遅延 / forget:忘れる"
  },
  {
    id: 227,
    type: "vocabulary",
    question: "The company plans to ______ expenses.",
    choices: ["cut", "increase", "ignore", "create"],
    answer: "cut",
    translation: "会社は経費を削減する予定だ",
    comment: "cut:削減 / increase:増加 / ignore:無視 / create:作成"
  },
  {
    id: 228,
    type: "vocabulary",
    question: "The report will ______ key issues.",
    choices: ["address", "ignore", "hide", "forget"],
    answer: "address",
    translation: "報告書は重要な問題を扱うだろう",
    comment: "address:扱う / ignore:無視 / hide:隠す / forget:忘れる"
  },
  {
    id: 229,
    type: "vocabulary",
    question: "The company must ______ regulations.",
    choices: ["comply with", "ignore", "break", "avoid"],
    answer: "comply with",
    translation: "会社は規則に従わなければならない",
    comment: "comply with:従う / ignore:無視 / break:破る / avoid:避ける"
  },
  {
    id: 230,
    type: "vocabulary",
    question: "The manager will ______ performance reviews.",
    choices: ["conduct", "ignore", "cancel", "forget"],
    answer: "conduct",
    translation: "マネージャーは業績評価を実施するだろう",
    comment: "conduct:実施 / ignore:無視 / cancel:中止 / forget:忘れる"
  },

  {
    id: 231,
    type: "vocabulary",
    question: "The company aims to ______ productivity.",
    choices: ["boost", "reduce", "ignore", "stop"],
    answer: "boost",
    translation: "会社は生産性を高めることを目指している",
    comment: "boost:高める / reduce:減らす / ignore:無視 / stop:停止"
  },
  {
    id: 232,
    type: "vocabulary",
    question: "The employee was asked to ______ the issue.",
    choices: ["investigate", "ignore", "hide", "forget"],
    answer: "investigate",
    translation: "その従業員は問題を調査するよう求められた",
    comment: "investigate:調査 / ignore:無視 / hide:隠す / forget:忘れる"
  },
  {
    id: 233,
    type: "vocabulary",
    question: "The company will ______ new opportunities.",
    choices: ["pursue", "ignore", "avoid", "destroy"],
    answer: "pursue",
    translation: "会社は新しい機会を追求するだろう",
    comment: "pursue:追求 / ignore:無視 / avoid:避ける / destroy:破壊"
  },
  {
    id: 234,
    type: "vocabulary",
    question: "The manager decided to ______ the offer.",
    choices: ["accept", "reject", "ignore", "forget"],
    answer: "accept",
    translation: "マネージャーはその提案を受け入れることにした",
    comment: "accept:受け入れる / reject:拒否 / ignore:無視 / forget:忘れる"
  },
  {
    id: 235,
    type: "vocabulary",
    question: "The company needs to ______ efficiency.",
    choices: ["maintain", "destroy", "ignore", "reduce"],
    answer: "maintain",
    translation: "会社は効率を維持する必要がある",
    comment: "maintain:維持 / destroy:破壊 / ignore:無視 / reduce:減少"
  },

  {
    id: 236,
    type: "vocabulary",
    question: "The employee was ______ for his contribution.",
    choices: ["thanked", "ignored", "punished", "delayed"],
    answer: "thanked",
    translation: "その従業員は貢献に対して感謝された",
    comment: "thanked:感謝 / ignored:無視 / punished:罰 / delayed:遅延"
  },
  {
    id: 237,
    type: "vocabulary",
    question: "The company will ______ its database.",
    choices: ["update", "destroy", "ignore", "forget"],
    answer: "update",
    translation: "会社はデータベースを更新するだろう",
    comment: "update:更新 / destroy:破壊 / ignore:無視 / forget:忘れる"
  },
  {
    id: 238,
    type: "vocabulary",
    question: "The manager asked the team to ______ results.",
    choices: ["report", "ignore", "hide", "forget"],
    answer: "report",
    translation: "マネージャーはチームに結果を報告するよう求めた",
    comment: "report:報告 / ignore:無視 / hide:隠す / forget:忘れる"
  },
  {
    id: 239,
    type: "vocabulary",
    question: "The company aims to ______ its global presence.",
    choices: ["expand", "reduce", "ignore", "stop"],
    answer: "expand",
    translation: "会社は世界的な存在感を拡大することを目指している",
    comment: "expand:拡大 / reduce:縮小 / ignore:無視 / stop:停止"
  },
  {
    id: 240,
    type: "vocabulary",
    question: "The report will ______ important data.",
    choices: ["include", "exclude", "ignore", "forget"],
    answer: "include",
    translation: "報告書は重要なデータを含むだろう",
    comment: "include:含む / exclude:除外 / ignore:無視 / forget:忘れる"
  },

  {
    id: 241,
    type: "vocabulary",
    question: "The company must ______ deadlines.",
    choices: ["meet", "miss", "ignore", "delay"],
    answer: "meet",
    translation: "会社は締め切りを守らなければならない",
    comment: "meet:守る / miss:逃す / ignore:無視 / delay:遅らせる"
  },
  {
    id: 242,
    type: "vocabulary",
    question: "The manager will ______ the project plan.",
    choices: ["approve", "reject", "ignore", "delay"],
    answer: "approve",
    translation: "マネージャーはプロジェクト計画を承認するだろう",
    comment: "approve:承認 / reject:却下 / ignore:無視 / delay:遅延"
  },
  {
    id: 243,
    type: "vocabulary",
    question: "The company plans to ______ costs significantly.",
    choices: ["cut", "increase", "ignore", "create"],
    answer: "cut",
    translation: "会社はコストを大幅に削減する予定だ",
    comment: "cut:削減 / increase:増加 / ignore:無視 / create:作成"
  },
  {
    id: 244,
    type: "vocabulary",
    question: "The employee was asked to ______ the data carefully.",
    choices: ["analyze", "ignore", "destroy", "forget"],
    answer: "analyze",
    translation: "その従業員はデータを注意深く分析するよう求められた",
    comment: "analyze:分析 / ignore:無視 / destroy:破壊 / forget:忘れる"
  },
  {
    id: 245,
    type: "vocabulary",
    question: "The company will ______ its services globally.",
    choices: ["offer", "remove", "ignore", "destroy"],
    answer: "offer",
    translation: "会社はサービスを世界的に提供するだろう",
    comment: "offer:提供 / remove:削除 / ignore:無視 / destroy:破壊"
  },

  {
    id: 246,
    type: "vocabulary",
    question: "The manager decided to ______ the schedule.",
    choices: ["revise", "ignore", "cancel", "forget"],
    answer: "revise",
    translation: "マネージャーはスケジュールを修正することにした",
    comment: "revise:修正 / ignore:無視 / cancel:中止 / forget:忘れる"
  },
  {
    id: 247,
    type: "vocabulary",
    question: "The company aims to ______ customer loyalty.",
    choices: ["build", "destroy", "ignore", "reduce"],
    answer: "build",
    translation: "会社は顧客の忠誠心を築くことを目指している",
    comment: "build:築く / destroy:破壊 / ignore:無視 / reduce:減少"
  },
  {
    id: 248,
    type: "vocabulary",
    question: "The employee was ______ for his achievements.",
    choices: ["recognized", "ignored", "punished", "delayed"],
    answer: "recognized",
    translation: "その従業員は成果で評価された",
    comment: "recognized:評価 / ignored:無視 / punished:罰 / delayed:遅延"
  },
  {
    id: 249,
    type: "vocabulary",
    question: "The company will ______ new products next year.",
    choices: ["launch", "cancel", "ignore", "destroy"],
    answer: "launch",
    translation: "会社は来年新製品を発売する予定だ",
    comment: "launch:発売 / cancel:中止 / ignore:無視 / destroy:破壊"
  },
  {
    id: 250,
    type: "vocabulary",
    question: "The manager asked employees to ______ the guidelines.",
    choices: ["follow", "ignore", "break", "forget"],
    answer: "follow",
    translation: "マネージャーは従業員にガイドラインに従うよう求めた",
    comment: "follow:従う / ignore:無視 / break:破る / forget:忘れる"
  }
];
